// The puzzle set. Generated by scripts/generate-levels.mjs, which scatters the
// five klossete pieces on a 15 mm-cell board and BFS-verifies each layout, so
// every level ships with a known minimum-move solution.
import raw from "./levels.json"
import type { PieceKind } from "./blocks"

export const GAP_CELLS = 2 // the exit gap is exactly one hero wide

export type LevelPiece = {
  kind: PieceKind
  x: number // left column of the footprint
  y: number // top row of the footprint (row 0 = the exit wall)
  rot: 0 | 1 // 1 = turned 90° (planks lying across the board)
}

export type Level = {
  id: string
  cols: number
  rows: number
  gapX: number // left column of the 2-wide exit gap in the top wall
  minMoves: number // BFS-verified minimum number of slides
  pieces: LevelPiece[] // pieces[0] is always the red cylinder (the hero)
}

export const LEVELS = raw as Level[]
